config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :customers do
    get 'alphabetized', on: :collection
    get 'missing_email', on: :collection
  end
  root 'customers#index'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  validates :full_name, presence:true
  belongs_to :province
end

app/models/province.rb
class Province < ApplicationRecord
  has_many :customers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end

  def alphabetized
    @customers = Customer.all.order(:full_name)
  end

  def missing_email
    @customers = Customer.where(email:'')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_customer.html.erb
<div class="customer">
  <h2><%= customer.full_name %></h2>
  <%= image_tag(customer.image) %>
  <p><strong>Province: </strong><%= customer.province == nil ? 'None' : customer.province.name %></p>
  <p><%= customer.phone_number %></p>
  <p><%= customer.email %> </p>
</div>

app/views/customers/alphabetized.html.erb
<h2>Customers Sorted by Full Name</h2>
<%= render partial: 'customer', collection: @customers, as: :customer %>

app/views/customers/index.html.erb
<h1>All Customers</h1>
<%= render partial: 'customer',
           collection: @customers, as: :customer %>

app/views/customers/missing_email.html.erb
<h2>Customers With Out Emails</h2>
<%= render partial: 'customer', collection: @customers, as: :customer %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UC6</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="topnav">
      <%= link_to "All Customers", root_path %>
      <%= link_to "Alphabetized Customers", alphabetized_customers_path %>
      <%= link_to "Customers without emails", missing_email_customers_path %>
    </div>
    <%= yield %>
  </body>
</html>